language: ruby
rvm:
- 2.6.3
- 2.7.0-preview1
- ruby-head
# gemfile: "gems.rb"
addons:
  postgresql: "9.6"
before_install:
- gem install bundler
before_script:
- cp config/.travis.database.yml config/database.yml
- psql -c 'create database travis_test;' -U postgres
matrix:
  allow_failures:
  - rvm: 2.7.0-preview1
  - rvm: ruby-head
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: us-east-1
    app: slice
    env: slice-production
    bucket_name: elasticbeanstalk-us-east-1-846666392784
    on:
      repo: sleepepi/slice
      branch: 78-0-stable
      rvm: 2.6.3
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: us-east-1
    app: slice
    env: slice-production-worker
    bucket_name: elasticbeanstalk-us-east-1-846666392784
    on:
      repo: sleepepi/slice
      branch: 78-0-stable
      rvm: 2.6.3
